spring:
  application:
    name: GX_OrderSystem
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./gx_order.db
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

server:
  port: 8081
